import { Position } from "@/lib/maze/types";

/**
 * Helper to convert a position into a string key for Set lookups.
 */
const toKey = (p: Position): string => `${p.row},${p.col}`;

/**
 * Filters a massive list of paths by removing macroscopically redundant routes
 * using the Jaccard Similarity Index.
 * 
 * @param allPaths Raw paths generated by the solving algorithm
 * @param threshold Maximum allowed similarity percentage (0.0 to 1.0)
 */
export function filterRedundantPaths(
  allPaths: Position[][],
  threshold: number = 0.90
): Position[][] {
  if (allPaths.length === 0) return [];

  // Sort from longest to shortest to preserve non-optimal variations as base shapes
  const sortedPaths = [...allPaths].sort((a, b) => b.length - a.length);
  
  const uniquePaths: Position[][] = [sortedPaths[0]];
  const selectedPathSets: Set<string>[] = [new Set(sortedPaths[0].map(toKey))];

  for (let i = 1; i < sortedPaths.length; i++) {
    const currentPath = sortedPaths[i];
    const currentSet = new Set(currentPath.map(toKey));
    let isRedundant = false;

    // Compare against already preserved macro-paths
    for (const savedSet of selectedPathSets) {
      let intersectionSize = 0;
      
      for (const cellKey of currentSet) {
        if (savedSet.has(cellKey)) {
          intersectionSize++;
        }
      }

      const unionSize = savedSet.size + currentSet.size - intersectionSize;
      const jaccardIndex = intersectionSize / unionSize;

      // Drop path if it exceeds the similarity threshold
      if (jaccardIndex > threshold) {
        isRedundant = true;
        break;
      }
    }

    if (!isRedundant) {
      uniquePaths.push(currentPath);
      selectedPathSets.push(currentSet);
    }
  }

  return uniquePaths;
}